### ISSUE TITLE
CUDA运行core dump了

### ISSUE THREAD

**Issue by Ivy233** [lovemefan/SenseVoice.cpp#41]
![image](https://github.com/user-attachments/assets/efe8dd72-ec3a-4d38-8d33-ff83ed9510f6)
看起来是接入vad后导致的，可能要找一下vad本身的原因？

**Comment by Niche180** [comment]
找到解决办法了吗，我也遇到了这个问题

**Comment by Niche180** [comment]
运行命令：./bin/sense-voice-main -m ../SenseVoiceGGUF/sense-voice-small-q4_1.gguf -f /root/warmup.wav

报错信息：
sense_voice_small_init_from_file_with_params_no_state: loading model from '../SenseVoiceGGUF/sense-voice-small-q4_1.gguf'
sense_voice_init_with_params_no_state: use gpu    = 1
sense_voice_init_with_params_no_state: flash attn = 0
sense_voice_init_with_params_no_state: gpu_device = 0
ggml_cuda_init: GGML_CUDA_FORCE_MMQ:    no
ggml_cuda_init: GGML_CUDA_FORCE_CUBLAS: no
ggml_cuda_init: found 1 CUDA devices:
  Device 0: NVIDIA GeForce RTX 3090, compute capability 8.6, VMM: yes
sense_voice_init_with_params_no_state: devices    = 2
sense_voice_init_with_params_no_state: backends   = 2
sense_voice_model_load: version:      3
sense_voice_model_load: alignment:   32
sense_voice_model_load: data offset: 423680
sense_voice_model_load: loading model
sense_voice_model_load: n_vocab = 25055
sense_voice_model_load: n_encoder_hidden_state = 512
sense_voice_model_load: n_encoder_linear_units = 2048
sense_voice_model_load: n_encoder_attention_heads  = 4
sense_voice_model_load: n_encoder_layers = 50
sense_voice_model_load: n_mels  = 80
sense_voice_model_load: ftype  = 3
sense_voice_model_load: vocab[25055] loaded
sense_voice_backend_init_gpu: using CUDA0 backend
sense_voice_model_load: CUDA0 total size =   195.57 MB
sense_voice_model_load: n_tensors: 1212
sense_voice_model_load: load SenseVoiceSmall takes 1.106000 second
sense_voice_backend_init_gpu: using CUDA0 backend
sense_voice_backend_init: using CPU backend
sense_voice_init_state: kv pad  size  =    3.67 MB
sense_voice_init_state: compute buffer (encoder)   =    3.09 MB
sense_voice_init_state: compute buffer (encoder)   =   17.58 MB
sense_voice_init_state: compute buffer (decoder)   =    5.58 MB

system_info: n_threads = 4 / 16 | AVX = 1 | AVX2 = 1 | AVX512 = 1 | FMA = 1 | NEON = 0 | ARM_FMA = 0 | F16C = 1 | FP16_VA = 0 | WASM_SIMD = 0 | SSE3 = 1 | SSSE3 = 1 | VSX = 0 | COREML = 0 | OPENVINO = 0

main: processing audio (692896 samples, 43.30600 sec) , 4 threads, 1 processors, lang = auto...

/mnt/home/jetvoice/workspace/SenseVoice.cpp/sense-voice/csrc/third-party/ggml/src/ggml-cuda/binbcast.cu:235: GGML_ASSERT(s10 == 1) failed
[New LWP 109239]
[New LWP 109240]
[New LWP 109241]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x000073ba440ea42f in __GI___wait4 (pid=109266, stat_loc=0x7ffdadcf6e34, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      ../sysdeps/unix/sysv/linux/wait4.c: 没有那个文件或目录.
#0  0x000073ba440ea42f in __GI___wait4 (pid=109266, stat_loc=0x7ffdadcf6e34, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30      in ../sysdeps/unix/sysv/linux/wait4.c
#1  0x00005c035b05fe2c in ggml_abort ()
#2  0x00005c035afeb6e5 in void bin_bcast_cuda<&(op_add(float, float))>::operator()<float, float, float>(ggml_tensor const*, ggml_tensor const*, ggml_tensor*, float const*, float const*, float*, CUstream_st*) [clone .constprop.0] ()
#3  0x00005c035aff3fd0 in ggml_cuda_op_add(ggml_backend_cuda_context&, ggml_tensor*) ()
#4  0x00005c035ae586d7 in ggml_backend_cuda_graph_compute(ggml_backend*, ggml_cgraph*) ()
#5  0x00005c035b07b998 in ggml_backend_sched_compute_splits(ggml_backend_sched*) ()
#6  0x00005c035b07cdb3 in ggml_backend_sched_graph_compute ()
#7  0x00005c035adf5014 in ggml_graph_compute_helper(ggml_backend_sched*, ggml_cgraph*, int) ()
#8  0x00005c035adccd96 in main ()
[Inferior 1 (process 109238) detached]
已中止

**Comment by lovemefan** [comment]
正在解决
